# Generated by Django 3.2.5 on 2021-08-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_photos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
